# Generated by Django 4.1 on 2022-08-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_auctionlistings_auctionlisting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
