# Generated by Django 4.1 on 2022-08-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctionlisting_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="auctionlisting", name="owner",),
    ]
