# Generated by Django 4.1 on 2022-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_auctionlisting_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="starting_bid",
            field=models.IntegerField(default="0"),
        ),
    ]
