# Generated by Django 4.1 on 2022-08-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auctionlisting_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.auctionlisting",
            ),
        ),
    ]
