# Generated by Django 4.1 on 2022-08-28 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_comment_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingBids",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highest_bid", models.IntegerField()),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Bid",),
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_url",
            field=models.URLField(
                default="https://media.istockphoto.com/vectors/no-image-available-sign-vector-id936182806?k=20&m=936182806&s=612x612&w=0&h=pTQbzaZhCTxWEDhnJlCS2gj65S926ABahbFCy5Np0jg=",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="listingbids",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
    ]
