# Generated by Django 4.1 on 2022-08-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_listingbids_delete_bid_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="ListingBids", new_name="ListingBid",),
    ]
