# Generated by Django 4.1 on 2022-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_rename_listingbids_listingbid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listingbid", old_name="highest_bid", new_name="bid_amount",
        ),
        migrations.RenameField(
            model_name="listingbid", old_name="highest_bidder", new_name="bidder",
        ),
        migrations.RemoveField(model_name="listingbid", name="listing",),
        migrations.AddField(
            model_name="auctionlisting",
            name="bids",
            field=models.ManyToManyField(
                blank=True, related_name="listing", to="auctions.listingbid"
            ),
        ),
    ]
