# Generated by Django 4.1 on 2022-08-30 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_rename_highest_bid_listingbid_bid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="bids",
            field=models.ManyToManyField(
                blank=True, related_name="bids", to="auctions.listingbid"
            ),
        ),
    ]
