# Generated by Django 4.1 on 2022-08-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_auctionlisting_watchers_alter_auctionlisting_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="winner",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
